### ISSUE TITLE
Question about middleware

### ISSUE THREAD

**Issue by arthurvanl** [DarthBenro008/melonpan#12]
Does express middleware work in this package?

I want to use mysql-express-session but i’m not sure if this is gonna work. Hope to hear from you!

**Comment by DarthBenro008** [comment]
Hey @arthurvanl ,


Currently `melonpan` does not support express middlewares due to type difference in the `Melonmiddleware` and `res` objects in `express` and `melonpan`.

The support can be considered to unlock a wide range of middlewares, but i am not sure the level of refactor is worth taking a hit on the performance, but can be considered for the future

Hence, unfortunately you will not be able to use the middleware as of yet.

Please feel free to reopen the issue if you feel the query has not been resolved!

**Comment by arthurvanl** [comment]
> Hey @arthurvanl ,
> 
> Currently `melonpan` does not support express middlewares due to type difference in the `Melonmiddleware` and `res` objects in `express` and `melonpan`.
> 
> The support can be considered to unlock a wide range of middlewares, but i am not sure the level of refactor is worth taking a hit on the performance, but can be considered for the future
> 
> Hence, unfortunately you will not be able to use the middleware as of yet.
> 
> Please feel free to reopen the issue if you feel the query has not been resolved!

Is there any middleware created yet?

**Comment by DarthBenro008** [comment]
You can create your own middleware using the following syntax:

```ts
const ml = new Melonpan();
ml.middleware((res, ctx, next) => {
// do your middleware logic here
next();
})

```

There will be middlewares such as `cors` and `body-parser` coming soon! Feel free to open a PR for any middlewares!
